- name: Disbale default redis version
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis version
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: update Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: update proctected-mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start redis System service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true