- name: Import Docker install file
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_install

- name: Start App container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    ports:
      - "8080"
    env:
      CATALOGUE_HOST:
      CATALOGUE_PORT:
      USER_HOST:
      USER_PORT:
      CART_HOST:
      CART_PORT:
      SHIPPING_HOST:
      SHIPPING_PORT:
      PAYMENT_HOST:
      PAYMENT_PORT: