- name: Import Java file
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install mysql
  ansible.builtin.dnf:
    name:
      - mysql
      - python3-mysqlclient
    state: installed

- name: load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/schema.sql
    login_host: mysql-dev.azdevops2704.online
    login_user: root
    login_password: RoboShop@1

- name: load app-user
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/app-user.sql
    login_host: mysql-dev.azdevops2704.online
    login_user: root
    login_password: RoboShop@1

- name: load master-data
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/master-data.sql
    login_host: mysql-dev.azdevops2704.online
    login_user: root
    login_password: RoboShop@1