- name: Copy rabbitmq repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start radditMq service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Add Application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/rabbitmq:AMQP_USER token={{ token }} url=http://vault-internal.azdevops2704.online:8200') }}"
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/rabbitmq:AMQP_PASS token={{ token }} url=http://vault-internal.azdevops2704.online:8200') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
