- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Set MySql Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/mysql:MYSQL_ROOTUSER token={{ vault_token }} url=http://vault.azdevops2704.online:8200') }}