- name: Copy dispatch service file
  ansible.builtin.copy:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Import App prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Build Go Project
  ansible.builtin.shell:
    - go mod init dispatch
    - go get
    - go build
  args:
    chdir: /app


- name: Import dispatch system service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
