- name: Copy dispatch service file
  ansible.builtin.copy:
    src: dispatch.service
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Import App prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Build Go Project
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize Go module
      command: go mod init dispatch

    - name: Get dependencies
      command: go get

    - name: Build Go project
      command: go build

- name: Import dispatch system service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
