- name: Creating a User
  ansible.builtin.user:
    name: roboshop

- name: Removing application directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating a new application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and extract Application
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes