- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Import App Prerequisites
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: install maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar
  args:
    chdir: /app

- name: Import System services
  ansible.builtin.include_tasks:
    file: systemd.yml