- name: Setup systemd service file
  ansible.builtin.copy:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ component_name }}.service

- name: Start Application server
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
